name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  GRADLE_OPTS: -Dorg.gradle.console=plain -Djava.security.egd=file:/dev/./urandom

jobs:
  matrix_build:
    name: "Matrix Build"
    runs-on:
      - ubuntu-latest
    container:
      image: azul/zulu-openjdk:17
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        spring_boot_version:
          - 3.3.1
          - 3.2.2
    env:
      SPRING_BOOT_VERSION: ${{ matrix.spring_boot_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: "Assemble jar"
        run: ./gradlew assemble --console=plain --info --stacktrace --parallel
      - name: "Compile tests"
        run: ./gradlew compileTestJava --console=plain --info --stacktrace --parallel
      - name: "Run checks"
        run: ./gradlew check -x test --console=plain --stacktrace
      - name: "Run tests"
        run: ./gradlew -Dspring.profiles.include=continuous-integration test --console=plain --info --stacktrace
      - name: "Test if publishing works"
        run: ./gradlew publishToMavenLocal --console=plain --info --stacktrace
      - name: "Publish Test Report"
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: Test Report-(${{ matrix.spring_boot_version }})
          report_paths: '**/build/test-results/**/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          require_tests: true
      - name: Publish checkstyle report
        if: always()
        uses: lcollins/checkstyle-github-action@v3.1.0
        with:
          name: Checkstyle Report-(${{ matrix.spring_boot_version }})
          path: '**/build/reports/**/*.xml'
      - name: Publish spotbugs report
        if: always()
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          name: Spotbugs Report-(${{ matrix.spring_boot_version }})
          path: '**/build/reports/**/*.xml'
      - name: "Collect test reports"
        run: |
          tar -zcvf all-test-reports-${{ matrix.spring_boot_version }}.tar.gz **/build/reports
        if: always()
      - name: "Store test results"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: all-test-reports-${{ matrix.spring_boot_version }}
          path: all-test-reports-${{ matrix.spring_boot_version }}.tar.gz
          retention-days: 7

  build:
    name: "Build and Test"
    runs-on:
      - ubuntu-latest
    needs: matrix_build
    steps:
      # Needed hacks to properly fail the build when one matrix build fails.
      - name: Do something so that GHA is happy
        run: echo "Be happy!"
      - name: Verify matrix jobs succeeded
        if: ${{ needs.matrix_build.result != 'success' }}
        run: exit 1
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: "Tag release"
        if: github.ref == 'refs/heads/master'
        run: ./gradlew tagRelease --console=plain --info --stacktrace
